server {
    listen 80;
    server_name localhost;
    
    # root /app;
    # index index.html;
    
    # location / {
    #     try_files $uri $uri/ /index.html;
    # }
    
    # # HTTP→HTTPS redirect, remove the above 
    # # and uncomment below (but then you can't serve files on 80):
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/conf.d/ssl/crt.crt;
    ssl_certificate_key /etc/nginx/conf.d/ssl/key.key;

    # root /app/templates;
    # index index.html;

    location /api/ollama/ {
        auth_basic "Auth Required";
        auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
        proxy_pass http://ollama:11434/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # location / {
    #     proxy_pass http://127.0.0.1:5000; 
    #     proxy_set_header Host $host;
    # }

    location /email {
        root /app/templates/; 
        # Tries to serve the file email.html. If it doesn't exist, return 404.
        try_files /email.html =404;
    }

    location / {
       
        root /app/templates/; 
        index index.html;
        try_files $uri $uri/ /index.html; # Essential for SPAs
    }

    location /api/{
        proxy_pass http://127.0.0.1:5000;
    }

    location /static/ {
        alias app/static/dist;
    }
}