from flask import Flask, request, jsonify
import requests

app = Flask(__name__)

OLLAMA_URL_G = 'http://ollama:11434/api/generate'
OLLAMA_URL_C = 'http://ollama:11434/api/chat'
@app.route('/api/email', methods=['POST'])
def generate_email():
    # Get the JSON data sent from the frontend
    data = request.get_json()

    if not data:
        return jsonify({"error": "Invalid JSON payload"}), 400

    recipient = data.get('recipient')
    subject = data.get('subject')
    tone = data.get('tone')
    key_points = data.get('key_points')

    if not all([recipient, subject, tone, key_points]):
        return jsonify({"error": "Missing one or more required fields (recipient, subject, tone, key_points)."}), 400

    prompt = f"""
    You are a highly professional email writing assistant. Your task is to draft a complete, coherent, and properly 
formatted email.
    
    Parameters:
    - Recipient: {recipient}
    - Subject: {subject}
    - Tone: {tone} (e.g., formal, casual, urgent)
    
    Key information points that MUST be covered in the email:
    {key_points}

    Instructions:
    1. Use a professional greeting (e.g., "Dear [Recipient Name]").
    2. Structure the email clearly around the key points.
    3. Conclude with a professional closing (e.g., "Best regards," or "Sincerely,").
    4. Do not include any extra commentary or introduction; provide only the draft email.
    """

   
    try:
   
        payload = {
            "model": "mistral", 
            "prompt": prompt,
            "stream": False     
        }
        
        # Make the API call
        response = requests.post(OLLAMA_URL_G, json=payload)
        response.raise_for_status() 

        llm_response = response.json()
        
        draft_text = llm_response.get('response', 'Error: No response generated by the LLM.')
        
        return jsonify({
            "success": True,
            "recipient": recipient,
            "subject": subject,
            "email_draft": draft_text.strip() # Clean up any whitespace
        })

    except requests.exceptions.ConnectionError:
        return jsonify({"error": "Could not connect to the Ollama service. Check if Ollama is running and accessible."}), 503
    except requests.exceptions.HTTPError as errh:
        return jsonify({"error": f"HTTP Error from Ollama API: {errh}"}), 502
    except requests.exceptions.RequestException as err:
        return jsonify({"error": f"An unexpected error occurred during the Ollama request: {err}"}), 500
    
@app.route('/api/chat', methods=['POST'])
def chat():
    data = request.get_json()
    
    model = data.get('model')
    conversation = data.get('messages')
    
    payload = {
        "model" : model,
        "messages" : conversation,
        "stream" : False
    }
    
    r = requests.post(OLLAMA_URL_C, json=payload)
    #returns the {content:--, role:"assistant"}
    data = r.json()
    
    return jsonify({"data": data.get('message')})

