from flask import Flask, request, jsonify
import requests

app = Flask(__name__)

# 2. NEW API ROUTE TO HANDLE THE FETCH REQUEST
@app.route('/api/email', methods=['POST'])
def generate_email():
    # Get the JSON data sent from the frontend
    data = request.get_json()

    if not data:
        return jsonify({"error": "Invalid JSON payload"}), 400

    # Extract the required fields
    recipient = data.get('recipient')
    subject = data.get('subject')
    tone = data.get('tone')
    key_points = data.get('key_points')

    if not all([recipient, subject, tone, key_points]):
        return jsonify({"error": "Missing one or more required fields (recipient, subject, tone, key_points)."}), 400

    # --- 🧠 CONSTRUCT THE LLM PROMPT ---
    # We create a detailed prompt to ensure the LLM does exactly what we want.
    prompt = f"""
    You are a highly professional email writing assistant. Your task is to draft a complete, coherent, and properly 
formatted email.
    
    Parameters:
    - Recipient: {recipient}
    - Subject: {subject}
    - Tone: {tone} (e.g., formal, casual, urgent)
    
    Key information points that MUST be covered in the email:
    {key_points}

    Instructions:
    1. Use a professional greeting (e.g., "Dear [Recipient Name]").
    2. Structure the email clearly around the key points.
    3. Conclude with a professional closing (e.g., "Best regards," or "Sincerely,").
    4. Do not include any extra commentary or introduction; provide only the draft email.
    """

    # --- 🛠️ CALL OLLAMA API ---
    try:
        # Payload structure for Ollama's generate endpoint
        payload = {
            "model": "llama2",  # <-- IMPORTANT: Replace 'llama2' with the model you have pulled in Ollama
            "prompt": prompt,
            "stream": False     # We want the full response at once
        }
        
        # Make the API call
        response = requests.post(OLLAMA_URL, json=payload)
        response.raise_for_status() # Raises an HTTPError if the status is 4xx or 5xx

        # Parse the response
        llm_response = response.json()
        
        # The generated text is usually under the 'response' key
        draft_text = llm_response.get('response', 'Error: No response generated by the LLM.')

        return jsonify({
            "success": True,
            "recipient": recipient,
            "subject": subject,
            "email_draft": draft_text.strip() # Clean up any whitespace
        })

    except requests.exceptions.ConnectionError:
        return jsonify({"error": "Could not connect to the Ollama service. Check if Ollama is running and accessible."}), 503
    except requests.exceptions.HTTPError as errh:
        return jsonify({"error": f"HTTP Error from Ollama API: {errh}"}), 502
    except requests.exceptions.RequestException as err:
        return jsonify({"error": f"An unexpected error occurred during the Ollama request: {err}"}), 500